a = input('Digite algo: ')
print('O tipo primitivo do seu valor é',type(a))
print('Só tem espaços?',a.isspace())
print('É só número?',a.isnumeric())
print('É só letra',a.isalpha())
print('tem número e letra?',a.isalnum())
